version: '3.8'
services:
  backend:
    image: alee444/backend-java:v1
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/project_uploads:/app/uploads
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-broad-mud-agt6onpr-pooler.c-2.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_mh43eLWwfNtQ
  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    environment:
      NGROK_AUTHTOKEN: 3BOhzRobb0R185amYJgxOVpcSan_4GoDB8objxbB3euFMaqS2
    command:
      - "http"
      - "--url=posticteric-tonnishly-leonida.ngrok-free.dev"
      - "backend:8080"
    depends_on:
      - backend