spring.application.name=BugBoard26
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bb26_db}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:Gold1}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
file.upload-dir=${UPLOAD_DIR:/app/uploads}
spring.jackson.serialization.write-dates-as-timestamps=false